<?php 
    header("Content-type: application/vnd.ms-excel");
    header("Content-Disposition: attachment;Filename=document_name.xls");
    echo "<html>";
    echo "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">";
    echo '<body style="font-family: Khmer MEF1">';
        echo '<center><br> <span class="font-mef2" style="color: rgb(13, 114, 162); font-size: 10pt;">
        របាយការណ៍សង្ខេបនៃការប្រើប្រាស់ចំណូលមិនមែនសារពើពន្ធរបស់ក្រសួង-ស្ថាប័ន<br>
        ប្រមូលសម្រាប់ការផ្តល់ការលើកទឹកចិត្តលើការងារកែទម្រង់ការគ្រប់គ្រងហិរញ្ញវត្ថុសាធារណៈ ឆ្នាំ២០២១<br></span> <div class="clearfix"></div> <br></center>';
        echo '<table border="1" class="table"><thead><tr style="background: rgb(227, 227, 227);"><th><center>ល.រ</center></th> <th><center>កូដ+អង្គភាព</center></th> <th colspan="2"><center>បណ្តាឆ្នាំមុន <span class="color-blue">*</span></center></th> <th colspan="2"><center>ក្នុងឆ្នាំ <span class="color-blue">**</span></center></th> <th colspan="2"><center>បូកយោង</center></th> <th rowspan="1"><center>សមតុល្យ</center></th></tr> <tr><th colspan="2"><center></center></th> <th style="color: green;"><center>ចំណូល</center></th> <th style="color: red;"><center>ចំណាយ</center></th> <th style="color: green;"><center>ចំណូល</center></th> <th style="color: red;"><center>ចំណាយ</center></th> <th style="color: green;"><center>ចំណូល</center></th> <th style="color: red;"><center>ចំណាយ</center></th> <th></th></tr></thead> <tr data="[object Object]"><td><center>1</center></td> <td><b>17-គណៈកម្មការមូលបត្រកម្ពុជា</b></td> <td><span><center>-</center></span></td> <td><span>297,200,000</span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span>297,200,000</span></td> <td><span style="color: red;">
        -297,200,000
    </span></td></tr><tr data="[object Object]"><td><center>2</center></td> <td><b>20-ក្រសួងអប់រំ យុវជន និងកីឡា</b></td> <td><span>17,303,500</span></td> <td><span>401,200,000</span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span>17,303,500</span></td> <td><span>401,200,000</span></td> <td><span style="color: red;">
        -383,896,500
    </span></td></tr><tr data="[object Object]"><td><center>3</center></td> <td><b>21-ក្រសួងសង្គមកិច្ច អតីតយុទ្ធជន និងយុនីតិសម្បទា</b></td> <td><span><center>-</center></span></td> <td><span>249,600,000</span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span>249,600,000</span></td> <td><span style="color: red;">
        -249,600,000
    </span></td></tr><tr data="[object Object]"><td><center>4</center></td> <td><b>22-ក្រសួងធម្មការ និងសាសនា</b></td> <td><span><center>-</center></span></td> <td><span>223,900,000</span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span>223,900,000</span></td> <td><span style="color: red;">
        -223,900,000
    </span></td></tr><tr data="[object Object]"><td><center>5</center></td> <td><b>23-ក្រសួងមហាផ្ទៃ-ផ្នែករដ្ឋបាលទូទៅ</b></td> <td><span><center>-</center></span></td> <td><span>401,200,000</span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span>401,200,000</span></td> <td><span style="color: red;">
        -401,200,000
    </span></td></tr><tr data="[object Object]"><td><center>6</center></td> <td><b>24-ក្រសួងមហាផ្ទៃ-ផ្នែកសន្តិសុខ</b></td> <td><span>4,968,842,239.71</span></td> <td><span>402,400,000</span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span>4,968,842,239.71</span></td> <td><span>402,400,000</span></td> <td><span style="color: green;">
        4,566,442,239.71
    </span></td></tr><tr data="[object Object]"><td><center>7</center></td> <td><b>25-ក្រសួងបរិស្ថាន</b></td> <td><span>250,829,193.8</span></td> <td><span>333,200,000</span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span>250,829,193.8</span></td> <td><span>333,200,000</span></td> <td><span style="color: red;">
        -82,370,806.2
    </span></td></tr><tr data="[object Object]"><td><center>8</center></td> <td><b>26-ក្រសួងរៀបចំដែនដី នគរូបនីយកម្ម និងសំណង់</b></td> <td><span>680,743,614</span></td> <td><span>329,200,000</span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span>680,743,614</span></td> <td><span>329,200,000</span></td> <td><span style="color: green;">
        351,543,614
    </span></td></tr><tr data="[object Object]"><td><center>9</center></td> <td><b>27-ក្រសួងមុខងារសាធារណៈ</b></td> <td><span><center>-</center></span></td> <td><span>411,400,000</span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span>411,400,000</span></td> <td><span style="color: red;">
        -411,400,000
    </span></td></tr><tr data="[object Object]"><td><center>10</center></td> <td><b>28-ក្រសួងវប្បធម៌ និងវិចិត្រសិល្បៈ</b></td> <td><span>384,385,306.75</span></td> <td><span>401,200,000</span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span>384,385,306.75</span></td> <td><span>401,200,000</span></td> <td><span style="color: red;">
        -16,814,693.25
    </span></td></tr><tr data="[object Object]"><td><center>11</center></td> <td><b>29-ក្រុមប្រឹក្សាអភិវឌ្ឍន៍កម្ពុជា</b></td> <td><span>1,348,061,435</span></td> <td><span>401,200,000</span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span>1,348,061,435</span></td> <td><span>401,200,000</span></td> <td><span style="color: green;">
        946,861,435
    </span></td></tr><tr data="[object Object]"><td><center>12</center></td> <td><b>30-ក្រសួងទំនាក់ទំនងជាមួយរដ្ឋសភា-ព្រឹទ្ធសភា និងអធិការកិច្ច</b></td> <td><span><center>-</center></span></td> <td><span>367,200,000</span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span>367,200,000</span></td> <td><span style="color: red;">
        -367,200,000
    </span></td></tr><tr data="[object Object]"><td><center>13</center></td> <td><b>31-គណៈកម្មាធិការជាតិរៀបចំការបោះឆ្នោត</b></td> <td><span><center>-</center></span></td> <td><span>231,200,000</span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span>231,200,000</span></td> <td><span style="color: red;">
        -231,200,000
    </span></td></tr><tr data="[object Object]"><td><center>14</center></td> <td><b>32-អាជ្ញាធរសវនកម្មជាតិ</b></td> <td><span><center>-</center></span></td> <td><span>401,200,000</span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span>401,200,000</span></td> <td><span style="color: red;">
        -401,200,000
    </span></td></tr><tr data="[object Object]"><td><center>15</center></td> <td><b>33-ឧស្សាហកម្ម វិទ្យាសាស្ត្រ បច្ចេកវិទ្យា និងនវានុវត្តន៍</b></td> <td><span>240,870,124</span></td> <td><span>401,200,000</span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span>240,870,124</span></td> <td><span>401,200,000</span></td> <td><span style="color: red;">
        -160,329,876
    </span></td></tr><tr data="[object Object]"><td><center>16</center></td> <td><b>34-រដ្ឋលេខាធិការដ្ឋានអាកាសចរណ៍ស៊ីវិល</b></td> <td><span>3,241,225,462.97</span></td> <td><span>401,200,000</span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span>3,241,225,462.97</span></td> <td><span>401,200,000</span></td> <td><span style="color: green;">
        2,840,025,462.97
    </span></td></tr><tr data="[object Object]"><td><center>17</center></td> <td><b>35-ទីស្តីការគណៈរដ្ឋមន្ត្រី</b></td> <td><span>119,766,000</span></td> <td><span>285,200,000</span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span>119,766,000</span></td> <td><span>285,200,000</span></td> <td><span style="color: red;">
        -165,434,000
    </span></td></tr><tr data="[object Object]"><td><center>18</center></td> <td><b>36-ក្រសួងរ៉ែនិងថាមពល</b></td> <td><span>385,964,620.18</span></td> <td><span>401,200,000</span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span>385,964,620.18</span></td> <td><span>401,200,000</span></td> <td><span style="color: red;">
        -15,235,379.82
    </span></td></tr><tr data="[object Object]"><td><center>19</center></td> <td><b>37-ក្រសួងពាណិជ្ជកម្ម</b></td> <td><span>3,782,307,866.4</span></td> <td><span>401,200,000</span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span>3,782,307,866.4</span></td> <td><span>401,200,000</span></td> <td><span style="color: green;">
        3,381,107,866.4
    </span></td></tr><tr data="[object Object]"><td><center>20</center></td> <td><b>38-ក្រសួងកសិកម្ម រុក្ខាប្រមាញ់ និងនេសាទ</b></td> <td><span>850,625,812.57</span></td> <td><span>377,200,000</span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span>850,625,812.57</span></td> <td><span>377,200,000</span></td> <td><span style="color: green;">
        473,425,812.57
    </span></td></tr><tr data="[object Object]"><td><center>21</center></td> <td><b>39-ក្រសួងអភិវឌ្ឍន៍ជនបទ</b></td> <td><span><center>-</center></span></td> <td><span>401,200,000</span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span>401,200,000</span></td> <td><span style="color: red;">
        -401,200,000
    </span></td></tr><tr data="[object Object]"><td><center>22</center></td> <td><b>40-ក្រសួងសាធារណការ និងដឹកជញ្ជូន</b></td> <td><span>559,097,165</span></td> <td><span>350,200,000</span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span>559,097,165</span></td> <td><span>350,200,000</span></td> <td><span style="color: green;">
        208,897,165
    </span></td></tr><tr data="[object Object]"><td><center>23</center></td> <td><b>41-ក្រសួងធនធានទឹក និងឧតុនិយម</b></td> <td><span><center>-</center></span></td> <td><span>401,200,000</span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span>401,200,000</span></td> <td><span style="color: red;">
        -401,200,000
    </span></td></tr><tr data="[object Object]"><td><center>24</center></td> <td><b>42-ក្រសួងការងារ និងបណ្តុះបណ្តាលវិជ្ជាជីវៈ</b></td> <td><span>2,079,917,700</span></td> <td><span>411,200,000</span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span>2,079,917,700</span></td> <td><span>411,200,000</span></td> <td><span style="color: green;">
        1,668,717,700
    </span></td></tr><tr data="[object Object]"><td><center>25</center></td> <td><b>43-ក្រសួងការពារជាតិ</b></td> <td><span><center>-</center></span></td> <td><span>334,700,000</span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span>334,700,000</span></td> <td><span style="color: red;">
        -334,700,000
    </span></td></tr><tr data="[object Object]"><td><center>26</center></td> <td><b>44-ក្រសួងកិច្ចការនារី</b></td> <td><span><center>-</center></span></td> <td><span>321,200,000</span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span>321,200,000</span></td> <td><span style="color: red;">
        -321,200,000
    </span></td></tr><tr data="[object Object]"><td><center>27</center></td> <td><b>45-ក្រសួងទេសចរណ៍</b></td> <td><span>107,864,765</span></td> <td><span>401,200,000</span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span>107,864,765</span></td> <td><span>401,200,000</span></td> <td><span style="color: red;">
        -293,335,235
    </span></td></tr><tr data="[object Object]"><td><center>28</center></td> <td><b>46-អគ្គលេខាធិការដ្ឋានរដ្ឋសភា</b></td> <td><span><center>-</center></span></td> <td><span>299,200,000</span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span>299,200,000</span></td> <td><span style="color: red;">
        -299,200,000
    </span></td></tr><tr data="[object Object]"><td><center>29</center></td> <td><b>47-ក្រសួងផែនការ</b></td> <td><span><center>-</center></span></td> <td><span>401,200,000</span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span>401,200,000</span></td> <td><span style="color: red;">
        -401,200,000
    </span></td></tr><tr data="[object Object]"><td><center>30</center></td> <td><b>48-អង្គភាពប្រឆាំងអំពើពុករលួយ</b></td> <td><span><center>-</center></span></td> <td><span>391,200,000</span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span>391,200,000</span></td> <td><span style="color: red;">
        -391,200,000
    </span></td></tr><tr data="[object Object]"><td><center>31</center></td> <td><b>49-ក្រសួងប្រៃសណីយ៍និងទូរគមនាគមន៍</b></td> <td><span>4,025,560,558.59</span></td> <td><span>401,200,000</span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span>4,025,560,558.59</span></td> <td><span>401,200,000</span></td> <td><span style="color: green;">
        3,624,360,558.59
    </span></td></tr><tr data="[object Object]"><td><center>32</center></td> <td><b>50-អគ្គលេខាធិការដ្ឋានព្រឹទ្ធសភា</b></td> <td><span><center>-</center></span></td> <td><span>333,200,000</span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span>333,200,000</span></td> <td><span style="color: red;">
        -333,200,000
    </span></td></tr><tr data="[object Object]"><td><center>33</center></td> <td><b>51-ឧត្តមក្រុមប្រឹក្សានៃអង្គចៅក្រម</b></td> <td><span><center>-</center></span></td> <td><span>207,200,000</span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span>207,200,000</span></td> <td><span style="color: red;">
        -207,200,000
    </span></td></tr><tr data="[object Object]"><td><center>34</center></td> <td><b>52-ក្រសួងសុខាភិបាល</b></td> <td><span>369,667,592.8</span></td> <td><span>401,200,000</span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span>369,667,592.8</span></td> <td><span>401,200,000</span></td> <td><span style="color: red;">
        -31,532,407.2
    </span></td></tr><tr data="[object Object]"><td><center>35</center></td> <td><b>53-ក្រសួងការបរទេស និងសហប្រតិបត្តិការអន្តរជាតិ</b></td> <td><span>1,314,775,745.65</span></td> <td><span>397,200,000</span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span>1,314,775,745.65</span></td> <td><span>397,200,000</span></td> <td><span style="color: green;">
        917,575,745.65
    </span></td></tr><tr data="[object Object]"><td><center>36</center></td> <td><b>54-សាលាឧទ្ធរណ៍</b></td> <td><span>50,874,118</span></td> <td><span>203,200,000</span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span>50,874,118</span></td> <td><span>203,200,000</span></td> <td><span style="color: red;">
        -152,325,882
    </span></td></tr><tr data="[object Object]"><td><center>37</center></td> <td><b>55-អគ្គលេខាធិការដ្ឋាននៃតុលាការកំពូល</b></td> <td><span>4,639,594</span></td> <td><span>163,200,000</span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span>4,639,594</span></td> <td><span>163,200,000</span></td> <td><span style="color: red;">
        -158,560,406
    </span></td></tr><tr data="[object Object]"><td><center>38</center></td> <td><b>56-អគ្គលេខាធិការដ្ឋានក្រុមប្រឹក្សាធម្មនុញ្ញ</b></td> <td><span><center>-</center></span></td> <td><span>231,200,000</span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span>231,200,000</span></td> <td><span style="color: red;">
        -231,200,000
    </span></td></tr><tr data="[object Object]"><td><center>39</center></td> <td><b>57-ក្រសួងព្រះបរមរាជវាំង</b></td> <td><span>509,643,330</span></td> <td><span>333,200,000</span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span>509,643,330</span></td> <td><span>333,200,000</span></td> <td><span style="color: green;">
        176,443,330
    </span></td></tr><tr data="[object Object]"><td><center>40</center></td> <td><b>58-ក្រសួងយុត្តិធម៌</b></td> <td><span>74,418,900</span></td> <td><span>287,200,000</span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span>74,418,900</span></td> <td><span>287,200,000</span></td> <td><span style="color: red;">
        -212,781,100
    </span></td></tr><tr data="[object Object]"><td><center>41</center></td> <td><b>59-ក្រសួងព័ត៌មាន</b></td> <td><span>52,546,841.5</span></td> <td><span>309,200,000</span></td> <td><span><center>-</center></span></td> <td><span><center>-</center></span></td> <td><span>52,546,841.5</span></td> <td><span>309,200,000</span></td> <td><span style="color: red;">
        -256,653,158.5
    </span></td></tr> <tr style="background-color: rgb(179, 230, 255);"><td colspan="2"><span class="font-mef2"><center>សរុប(គិតជារៀល)</center></span></td> <td><b style="text-decoration: underline;">25,419,931,485.92</b></td> <td><b style="text-decoration: underline;">14,098,200,000</b></td> <td><b style="text-decoration: underline;">0</b></td> <td><b style="text-decoration: underline;">0</b></td> <td><b style="text-decoration: underline;">25,419,931,485.92</b></td> <td><b style="text-decoration: underline;">14,098,200,000</b></td> <td><b style="text-decoration: underline;">11,321,731,485.92</b></td></tr> <tr style="background-color: rgb(179, 230, 255);"><td colspan="2"><span class="font-mef2"><center>សរុប(គិតជាដុល្លា)</center></span></td> <td><b style="text-decoration: underline;">$ 6,354,982.871</b></td> <td><b style="text-decoration: underline;">$ 3,524,550</b></td> <td><b style="text-decoration: underline;">$ 0</b></td> <td><b style="text-decoration: underline;">$ 0</b></td> <td><b style="text-decoration: underline;">$ 6,354,982.871</b></td> <td><b style="text-decoration: underline;">$ 3,524,550</b></td> <td><b style="text-decoration: underline;">$ 2,830,432.871</b></td></tr></table>';
    echo "</body>";
    echo "</html>";
?>